name: Go-Linux

on:
  push:
    branches:
      - main

jobs:
  build:
    timeout-minutes: 40
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ 'ubuntu-latest' ]
    steps:
      - name: Set up Go 1.17
        uses: actions/setup-go@v4
        with:
          go-version: 1.17
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Get dependencies
        working-directory: ./src/lagoon
        run: go get -v -t -d ./...

      - name: Set version as variable
        run: |
          VER=$(cat VERSION)
          echo "VERSION=$VER" >> $GITHUB_ENV

      - name: Build
        working-directory: ./src/lagoon
        run: mkdir lagoon-linux-amd64-${{ env.VERSION }} && go build -v -o lagoon-linux-amd64-${{ env.VERSION }} ./...

      - name: Upload binaries
        uses: actions/upload-artifact@v3
        with:
          name: lagoon-linux-amd64-${{ env.VERSION }}
          path: ./lagoon-*

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            aerisconsulting/lagoon:latest
            aerisconsulting/lagoon:${{ env.VERSION }}
