name: Go-Windows

on:
  push:
    branches:
      - main

jobs:
  build:
    timeout-minutes: 10
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ 'windows-latest' ]
    steps:
      - name: Set up Go 1.17
        uses: actions/setup-go@v4
        with:
          go-version: 1.17
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Get dependencies
        working-directory: ./src/lagoon
        run: go get -v -t -d ./...

      - name: Set version as variable
        run: | # Powershell
          $VER = Get-Content VERSION -Raw
          echo "Using the version $VER into $Env:GITHUB_ENV"
          "VERSION=$VER" >> $Env:GITHUB_ENV

      - name: Build
        working-directory: ./src/lagoon
        run: mkdir lagoon-windows-amd64-${{ env.VERSION }} && go build -v -o lagoon-windows-amd64-${{ env.VERSION }} ./...

      - name: Upload binaries
        uses: actions/upload-artifact@v3
        with:
          name: lagoon-windows-amd64-${{ env.VERSION }}
          path: ./lagoon-*