name: Go

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - master

jobs:
  build:
    timeout-minutes: 10
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-latest','windows-latest','macos-latest']
    steps:
      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Get dependencies
        working-directory: ./src/lagoon
        run: |
          go get -v -t -d ./...

      - name: Build
        working-directory: ./src/lagoon
        run: go build -v .
