name: Node CI

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    timeout-minutes: 10
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v3

      - name: Use Yarn
        uses: nuxt/actions-yarn@node-11

      - name: yarn install and test
        working-directory: ./ui
        run: |
          yarn
          yarn test:unit
        env:
          CI: true
